"""add field created_at model post

Revision ID: 686063c17bab
Revises: 1dd3d850b29d
Create Date: 2022-12-05 20:33:54.417770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686063c17bab'
down_revision = '1dd3d850b29d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_posts', 'created_at')
    # ### end Alembic commands ###
