# Generated by Django 4.1.4 on 2022-12-13 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_credito', to='financas.contafinanceira')),
                ('conta_debito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_debito', to='financas.contafinanceira')),
            ],
            options={
                'db_table': 'tb_transacoes',
            },
        ),
    ]
